name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: 'ubuntu-latest'
    name: 'Test code and build release binaries'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - name: 'Run tests'
        run: go test -v ./...
      - name: 'Build Linux binary'
        run: go build -o xml-to-graph
      - name: 'Build Windows binary'
        run: GOOS=windows go build -o xml-to-graph.exe
      - name: 'Release'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            xml-to-graph
            xml-to-graph.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
